import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const specification = resolve(process.env.SPEC ?? '../openapi/openapi.yaml')
const schema = await openapiTS(pathToFileURL(specification))
const banner = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`
const output = resolve('src/api/schema.d.ts')
mkdirSync(dirname(output), { recursive: true })
writeFileSync(output, banner + astToString(schema))
console.log(`${specification} -> src/api/schema.d.ts`)
