use std::{
    path::{Path, PathBuf},
    process::Stdio,
};

use axum::{
    body::Bytes,
    extract::{Path as AxumPath, Query, State},
    http::{HeaderMap, StatusCode, header},
    response::{IntoResponse, Response},
};
use base64::Engine;
use chrono::{DateTime, Utc};
use serde::Deserialize;
use sqlx::{FromRow, PgPool};
use tokio::{io::AsyncWriteExt, process::Command};
use uuid::Uuid;

use crate::api::{ApiError, AppState};

#[derive(Clone, Debug)]
pub struct GitConfig {
    pub root: PathBuf,
    pub token: Option<String>,
    pub internal_token: Option<String>,
}

impl Default for GitConfig {
    fn default() -> Self {
        Self {
            root: PathBuf::from("/tmp/forge-test-repos"),
            token: None,
            internal_token: None,
        }
    }
}

#[derive(Debug, serde::Serialize, FromRow, utoipa::ToSchema)]
pub struct Repository {
    pub id: Uuid,
    pub name: String,
    pub visibility: String,
    pub created_at: DateTime<Utc>,
}

/// Validates a repository name: ascii word chars, no leading dot, no `..`,
/// max 100 chars. The `.git` suffix is optional and stripped.
pub fn validate_repo_name(input: &str) -> Result<String, String> {
    let name = input.trim().trim_end_matches(".git");
    if name.is_empty() || name.len() > 100 {
        return Err("repository name must be 1-100 characters".into());
    }
    if !name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
    {
        return Err("repository name allows only letters, digits, '-', '_', '.'".into());
    }
    if name.starts_with('.') || name.contains("..") {
        return Err("repository name must not start with '.' or contain '..'".into());
    }
    Ok(name.to_string())
}

fn repo_path(root: &Path, name: &str) -> PathBuf {
    root.join(format!("{name}.git"))
}

fn post_receive_hook(name: &str, internal_token: Option<&str>) -> String {
    let token_header = internal_token
        .map(|t| format!("  -H 'x-internal-token: {t}' \\"))
        .unwrap_or_default();
    format!(
        r#"#!/bin/sh
# Auto-generated by Forge CI/CD. Triggers pipelines on push.
while read oldrev newrev refname; do
  curl -fsS -X POST "http://127.0.0.1:22801/api/v1/internal/git-push" \
    -H 'content-type: application/json' \
{token_header}
    -d "{{\"repository\":\"{name}\",\"ref_name\":\"$refname\",\"old_rev\":\"$oldrev\",\"new_rev\":\"$newrev\"}}" >/dev/null 2>&1 || true
done
"#
    )
}

pub async fn create_repository_core(
    pool: &PgPool,
    config: &GitConfig,
    raw_name: &str,
    visibility: Option<&str>,
) -> Result<Repository, ApiError> {
    let visibility = match visibility.unwrap_or("private") {
        "public" => "public".to_string(),
        _ => "private".to_string(),
    };
    let name = validate_repo_name(raw_name).map_err(ApiError::bad_request)?;
    let path = repo_path(&config.root, &name);
    if sqlx::query_scalar::<_, bool>("SELECT EXISTS(SELECT 1 FROM repositories WHERE name = $1)")
        .bind(&name)
        .fetch_one(pool)
        .await
        .map_err(ApiError::internal)?
    {
        return Err(ApiError::bad_request(format!(
            "repository '{name}' already exists"
        )));
    }
    tokio::fs::create_dir_all(&config.root)
        .await
        .map_err(|e| ApiError::internal(sqlx::Error::Io(e)))?;
    let status = Command::new("git")
        .args(["init", "--bare", "--quiet"])
        .arg(&path)
        .status()
        .await
        .map_err(|e| ApiError::internal(sqlx::Error::Io(e)))?;
    if !status.success() {
        return Err(ApiError::bad_request("git init failed"));
    }
    let hook_path = path.join("hooks").join("post-receive");
    tokio::fs::write(
        &hook_path,
        post_receive_hook(&name, config.internal_token.as_deref()),
    )
    .await
    .map_err(|e| ApiError::internal(sqlx::Error::Io(e)))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = std::fs::metadata(&hook_path) {
            let mut perms = meta.permissions();
            perms.set_mode(0o755);
            let _ = std::fs::set_permissions(&hook_path, perms);
        }
    }
    let repo = sqlx::query_as::<_, Repository>(
        "INSERT INTO repositories (id, name, visibility) VALUES ($1, $2, $3) RETURNING id, name, visibility, created_at",
    )
    .bind(Uuid::new_v4())
    .bind(&name)
    .bind(&visibility)
    .fetch_one(pool)
    .await
    .map_err(ApiError::internal)?;
    Ok(repo)
}

pub async fn list_repositories_core(pool: &PgPool) -> Result<Vec<Repository>, ApiError> {
    sqlx::query_as::<_, Repository>(
        "SELECT id, name, visibility, created_at FROM repositories ORDER BY created_at DESC",
    )
    .fetch_all(pool)
    .await
    .map_err(ApiError::internal)
}

pub async fn delete_repository_core(
    pool: &PgPool,
    config: &GitConfig,
    raw_name: &str,
) -> Result<(), ApiError> {
    let name = validate_repo_name(raw_name).map_err(ApiError::bad_request)?;
    let deleted =
        sqlx::query_scalar::<_, Uuid>("DELETE FROM repositories WHERE name = $1 RETURNING id")
            .bind(&name)
            .fetch_optional(pool)
            .await
            .map_err(ApiError::internal)?
            .ok_or_else(ApiError::not_found)?;
    let _ = deleted;
    let path = repo_path(&config.root, &name);
    let _ = tokio::fs::remove_dir_all(path).await;
    Ok(())
}

/// Checks basic-auth (any username + token as password) or `x-git-token`.
/// Clone/fetch is open for public repos; private repos keep the token gate.
/// Push (receive-pack) always requires the token.
pub async fn check_repo_access(
    state: &std::sync::Arc<AppState>,
    repo: &str,
    headers: &HeaderMap,
) -> Result<(), ApiError> {
    let is_push = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .map(|v| v.contains("git-receive-pack"))
        .unwrap_or(false)
        || headers
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .map(|v| v.contains("git-receive-pack"))
            .unwrap_or(false);
    if is_push {
        return check_git_auth(&state.git, headers);
    }
    // Public read check (best-effort, falls back to token gate on any error).
    let visibility = async {
        match state.pool.as_ref() {
            Some(pool) => sqlx::query_scalar::<_, String>(
                "SELECT visibility FROM repositories WHERE name = $1",
            )
            .bind(repo.trim_end_matches(".git"))
            .fetch_one(pool)
            .await
            .ok(),
            None => None,
        }
    }
    .await;
    match visibility.as_deref() {
        Some("public") => Ok(()),
        _ => check_git_auth(&state.git, headers),
    }
}

pub fn check_git_auth(config: &GitConfig, headers: &HeaderMap) -> Result<(), ApiError> {
    let Some(expected) = config.token.as_deref() else {
        return Ok(());
    };
    if expected.is_empty() {
        return Ok(());
    }
    if let Some(provided) = headers
        .get("x-git-token")
        .and_then(|v| v.to_str().ok())
        .filter(|v| *v == expected)
    {
        let _ = provided;
        return Ok(());
    }
    if let Some(value) = headers
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Basic "))
    {
        let decoded = base64::engine::general_purpose::STANDARD
            .decode(value)
            .map_err(|_| ApiError::unauthorized())?;
        let text = String::from_utf8_lossy(&decoded);
        if let Some((_, password)) = text.split_once(':') {
            if password == expected {
                return Ok(());
            }
        }
    }
    Err(ApiError::unauthorized())
}

fn pkt_line(payload: &str) -> Vec<u8> {
    format!("{:04x}{}", payload.len() + 4, payload).into_bytes()
}

#[derive(Deserialize, utoipa::IntoParams)]
#[into_params(parameter_in = Query)]
pub struct InfoRefsParams {
    service: Option<String>,
}

#[utoipa::path(
    get,
    path = "/git/{repo}/info/refs",
    tag = "git",
    params(
        ("repo" = String, Path, description = "Repository name"),
        ("service" = Option<String>, Query, description = "git-upload-pack or git-receive-pack"),
    ),
    responses(
        (status = 200, description = "Git Smart HTTP ref advertisement"),
        (status = 400, description = "Missing or unsupported service"),
        (status = 401),
        (status = 404),
    ),
)]
pub async fn git_info_refs(
    State(state): State<std::sync::Arc<AppState>>,
    AxumPath(repo): AxumPath<String>,
    Query(params): Query<InfoRefsParams>,
    headers: HeaderMap,
) -> Response {
    if let Err(e) = check_repo_access(&state, &repo, &headers).await {
        return e.into_response();
    }
    let service = match params.service.as_deref() {
        Some("git-upload-pack") => "upload-pack",
        Some("git-receive-pack") => "receive-pack",
        _ => {
            return ApiError::bad_request("service parameter is required").into_response();
        }
    };
    let pool = match state.pool.as_ref() {
        Some(pool) => pool,
        None => return ApiError::unavailable().into_response(),
    };
    let path = match resolve_repo_path(pool, &state.git, &repo).await {
        Ok(path) => path,
        Err(e) => return e.into_response(),
    };
    let output = match Command::new("git")
        .arg(service)
        .arg("--stateless-rpc")
        .arg("--advertise-refs")
        .arg(&path)
        .output()
        .await
    {
        Ok(output) => output,
        Err(e) => return ApiError::internal(sqlx::Error::Io(e)).into_response(),
    };
    if !output.status.success() {
        return ApiError::internal(sqlx::Error::Io(std::io::Error::other(
            String::from_utf8_lossy(&output.stderr).to_string(),
        )))
        .into_response();
    }
    let mut body = pkt_line(&format!("# service=git-{service}\n"));
    body.extend_from_slice(b"0000");
    body.extend_from_slice(&output.stdout);
    (
        StatusCode::OK,
        [(
            header::CONTENT_TYPE,
            format!("application/x-git-{service}-advertisement"),
        )],
        body,
    )
        .into_response()
}

fn maybe_gunzip(headers: &HeaderMap, body: Bytes) -> Result<Bytes, ApiError> {
    let gzipped = headers
        .get(header::CONTENT_ENCODING)
        .and_then(|v| v.to_str().ok())
        .is_some_and(|v| v.to_ascii_lowercase().contains("gzip"));
    if !gzipped {
        return Ok(body);
    }
    use std::io::Read;
    let mut decoder = flate2::read::GzDecoder::new(&body[..]);
    let mut out = Vec::new();
    decoder
        .read_to_end(&mut out)
        .map_err(|e| ApiError::internal(sqlx::Error::Io(e)))?;
    Ok(out.into())
}

async fn run_git_service(
    path: &Path,
    service: &str, // "upload-pack" | "receive-pack"
    body: Bytes,
) -> Result<Vec<u8>, ApiError> {
    let mut child = Command::new("git")
        .arg(service)
        .arg("--stateless-rpc")
        .arg(path)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| ApiError::internal(sqlx::Error::Io(e)))?;
    let mut stdin = child
        .stdin
        .take()
        .ok_or_else(|| ApiError::bad_request("failed to open stdin"))?;
    let payload = body.to_vec();
    let writer = tokio::spawn(async move {
        let _ = stdin.write_all(&payload).await;
        let _ = stdin.shutdown().await;
    });
    let output = child
        .wait_with_output()
        .await
        .map_err(|e| ApiError::internal(sqlx::Error::Io(e)))?;
    let _ = writer.await;
    if !output.status.success() {
        return Err(ApiError::internal(sqlx::Error::Io(std::io::Error::other(
            String::from_utf8_lossy(&output.stderr).to_string(),
        ))));
    }
    Ok(output.stdout)
}

#[utoipa::path(
    post,
    path = "/git/{repo}/git-upload-pack",
    tag = "git",
    request_body = Vec<u8>,
    params(("repo" = String, Path, description = "Repository name")),
    responses(
        (status = 200, description = "git-upload-pack or git-receive-pack result payload"),
        (status = 400, description = "Unsupported git service"),
        (status = 401),
        (status = 404),
    ),
)]
pub async fn git_service_endpoint(
    State(state): State<std::sync::Arc<AppState>>,
    AxumPath(repo): AxumPath<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Response {
    if let Err(e) = check_repo_access(&state, &repo, &headers).await {
        return e.into_response();
    }
    let service = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("application/x-git-"))
        .and_then(|v| v.strip_suffix("-request"))
        .unwrap_or("");
    let service = match service {
        "upload-pack" | "receive-pack" => service,
        _ => return ApiError::bad_request("unsupported git service").into_response(),
    };
    let pool = match state.pool.as_ref() {
        Some(pool) => pool,
        None => return ApiError::unavailable().into_response(),
    };
    let path = match resolve_repo_path(pool, &state.git, &repo).await {
        Ok(path) => path,
        Err(e) => return e.into_response(),
    };
    let body = match maybe_gunzip(&headers, body) {
        Ok(body) => body,
        Err(e) => return e.into_response(),
    };
    match run_git_service(path.as_path(), service, body).await {
        Ok(out) => (
            StatusCode::OK,
            [(
                header::CONTENT_TYPE,
                format!("application/x-git-{service}-result"),
            )],
            out,
        )
            .into_response(),
        Err(e) => e.into_response(),
    }
}

#[utoipa::path(
    post,
    path = "/git/{repo}/git-receive-pack",
    tag = "git",
    request_body = Vec<u8>,
    params(("repo" = String, Path, description = "Repository name")),
    responses(
        (status = 200, description = "git-receive-pack result payload"),
        (status = 400, description = "Unsupported git service"),
        (status = 401),
        (status = 404),
    ),
)]
#[allow(dead_code)]
pub async fn git_receive_pack_openapi() {}

async fn resolve_repo_path(
    pool: &PgPool,
    config: &GitConfig,
    raw: &str,
) -> Result<PathBuf, ApiError> {
    let name = validate_repo_name(raw).map_err(ApiError::bad_request)?;
    let exists =
        sqlx::query_scalar::<_, bool>("SELECT EXISTS(SELECT 1 FROM repositories WHERE name = $1)")
            .bind(&name)
            .fetch_one(pool)
            .await
            .map_err(ApiError::internal)?;
    if !exists {
        return Err(ApiError::not_found());
    }
    Ok(repo_path(&config.root, &name))
}

#[derive(Deserialize, utoipa::ToSchema)]
pub struct GitPushEvent {
    pub repository: String,
    pub ref_name: String,
    #[serde(default)]
    pub old_rev: Option<String>,
    #[serde(default)]
    pub new_rev: Option<String>,
}

/// Internal endpoint called by the generated `post-receive` hook.
/// Finds a project whose repository_url points at this repo and triggers a pipeline.
#[utoipa::path(
    post,
    path = "/api/v1/internal/git-push",
    tag = "git",
    request_body = GitPushEvent,
    responses(
        (status = 200, description = "Pipeline trigger decision"),
        (status = 400),
        (status = 401),
    ),
)]
pub async fn internal_git_push(
    State(state): State<std::sync::Arc<AppState>>,
    headers: HeaderMap,
    axum::Json(event): axum::Json<GitPushEvent>,
) -> Result<axum::Json<serde_json::Value>, ApiError> {
    if let Some(expected) = state.git.internal_token.as_deref() {
        if !expected.is_empty() {
            let provided = headers
                .get("x-internal-token")
                .and_then(|v| v.to_str().ok())
                .unwrap_or("");
            if provided != expected {
                return Err(ApiError::unauthorized());
            }
        }
    }
    let pool = state.pool.as_ref().ok_or_else(ApiError::unavailable)?;
    let name = validate_repo_name(&event.repository).map_err(ApiError::bad_request)?;
    let short_ref = event
        .ref_name
        .strip_prefix("refs/heads/")
        .or_else(|| event.ref_name.strip_prefix("refs/tags/"))
        .unwrap_or(&event.ref_name)
        .to_string();
    if event.new_rev.as_deref().is_some_and(is_zero_object_id) {
        return Ok(axum::Json(serde_json::json!({
            "triggered": false,
            "pipeline_id": null,
            "reason": "deleted_ref"
        })));
    }
    let idempotency_key = event
        .new_rev
        .as_deref()
        .filter(|rev| is_probable_object_id(rev))
        .map(|rev| git_push_idempotency_key(&name, &event.ref_name, rev));
    let pattern = format!("%{name}.git");
    let project_id: Option<Uuid> =
        sqlx::query_scalar("SELECT id FROM projects WHERE repository_url ILIKE $1 LIMIT 1")
            .bind(&pattern)
            .fetch_optional(pool)
            .await
            .map_err(ApiError::internal)?;
    match project_id {
        Some(project_id) => {
            let outcome = crate::api::create_pipeline_with_vars_idempotent(
                pool,
                project_id,
                short_ref,
                serde_json::json!({}),
                crate::api::PIPELINE_TRIGGER_SOURCE_GIT_PUSH,
                idempotency_key.as_deref(),
            )
            .await?;
            Ok(axum::Json(serde_json::json!({
                "triggered": true,
                "pipeline_id": outcome.pipeline.id,
                "replayed": outcome.replayed
            })))
        }
        None => Ok(axum::Json(
            serde_json::json!({"triggered": false, "pipeline_id": null}),
        )),
    }
}

fn is_zero_object_id(value: &str) -> bool {
    value.len() >= 40 && value.chars().all(|c| c == '0')
}

fn is_probable_object_id(value: &str) -> bool {
    value.len() >= 40 && value.chars().all(|c| c.is_ascii_hexdigit())
}

fn git_push_idempotency_key(repository: &str, ref_name: &str, new_rev: &str) -> String {
    use sha2::{Digest, Sha256};
    let payload = format!("{repository}\0{ref_name}\0{new_rev}");
    format!("git-push:{:x}", Sha256::digest(payload.as_bytes()))
}

// --- Axum HTTP handlers (thin wrappers over the core functions) ---

#[derive(Deserialize, utoipa::ToSchema)]
pub struct CreateRepositoryBody {
    pub name: String,
    #[serde(default)]
    pub visibility: Option<String>,
}

#[derive(Debug, serde::Serialize, utoipa::ToSchema)]
pub struct DeletedRepository {
    pub deleted: String,
}

#[utoipa::path(
    post,
    path = "/api/v1/repositories",
    tag = "repos",
    request_body = CreateRepositoryBody,
    responses(
        (status = 200, body = Repository),
        (status = 400),
        (status = 503),
    ),
)]
pub async fn create_repository(
    State(state): State<std::sync::Arc<AppState>>,
    axum::Json(body): axum::Json<CreateRepositoryBody>,
) -> Result<axum::Json<Repository>, ApiError> {
    let pool = state.pool.as_ref().ok_or_else(ApiError::unavailable)?;
    let repo =
        create_repository_core(pool, &state.git, &body.name, body.visibility.as_deref()).await?;
    Ok(axum::Json(repo))
}

#[utoipa::path(
    get,
    path = "/api/v1/repositories",
    tag = "repos",
    responses(
        (status = 200, body = [Repository]),
        (status = 503),
    ),
)]
pub async fn list_repositories(
    State(state): State<std::sync::Arc<AppState>>,
) -> Result<axum::Json<Vec<Repository>>, ApiError> {
    let pool = state.pool.as_ref().ok_or_else(ApiError::unavailable)?;
    let repos = list_repositories_core(pool).await?;
    Ok(axum::Json(repos))
}

#[utoipa::path(
    delete,
    path = "/api/v1/repositories/{name}",
    tag = "repos",
    params(("name" = String, Path, description = "Repository name")),
    responses(
        (status = 200, body = DeletedRepository),
        (status = 404),
        (status = 503),
    ),
)]
pub async fn delete_repository(
    State(state): State<std::sync::Arc<AppState>>,
    AxumPath(name): AxumPath<String>,
) -> Result<axum::Json<DeletedRepository>, ApiError> {
    let pool = state.pool.as_ref().ok_or_else(ApiError::unavailable)?;
    delete_repository_core(pool, &state.git, &name).await?;
    Ok(axum::Json(DeletedRepository {
        deleted: name.trim_end_matches(".git").to_string(),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_repo_names() {
        assert!(validate_repo_name("demo").is_ok());
        assert!(validate_repo_name("demo.git").is_ok());
        assert_eq!(validate_repo_name("demo.git").expect("valid name"), "demo");
        assert!(validate_repo_name("").is_err());
        assert!(validate_repo_name("../etc").is_err());
        assert!(validate_repo_name(".hidden").is_err());
        assert!(validate_repo_name("a..b").is_err());
        assert!(validate_repo_name("has space").is_err());
        assert!(validate_repo_name("спец").is_err());
    }

    #[test]
    fn pkt_line_prefix_is_hex_length() {
        let line = pkt_line("# service=git-upload-pack\n");
        assert_eq!(&line[..4], b"001e");
        assert!(line.ends_with(b"# service=git-upload-pack\n"));
    }

    #[tokio::test]
    async fn creates_and_deletes_bare_repository() {
        let dir = std::env::temp_dir().join(format!("forge-git-test-{}", Uuid::new_v4()));
        let config = GitConfig {
            root: dir.clone(),
            token: None,
            internal_token: Some("test-internal".into()),
        };
        tokio::fs::create_dir_all(&dir)
            .await
            .expect("create temp dir");
        // Minimal in-memory check is impossible without Postgres; verify hook + git layout directly.
        let path = repo_path(&dir, "demo");
        let status = Command::new("git")
            .args(["init", "--bare", "--quiet"])
            .arg(&path)
            .status()
            .await
            .expect("git init");
        assert!(status.success());
        assert!(path.join("HEAD").exists());
        let hook = post_receive_hook("demo", config.internal_token.as_deref());
        assert!(hook.contains("x-internal-token: test-internal"));
        assert!(hook.contains("demo"));
        assert!(hook.contains("$refname"));
        assert!(hook.contains("$oldrev"));
        assert!(hook.contains("$newrev"));
        assert!(hook.contains("/api/v1/internal/git-push"));
        let key = git_push_idempotency_key(
            "demo",
            "refs/heads/main",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        );
        assert!(key.starts_with("git-push:"));
        assert_ne!(
            key,
            git_push_idempotency_key(
                "demo",
                "refs/heads/main",
                "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
            )
        );
        let _ = tokio::fs::remove_dir_all(&dir).await;
    }
}
