use super::*;
use sqlx::Connection;

const SEED: &str = "CREATE TABLE public.records (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,payload text NOT NULL);\n";
const NEXT: &str = "ALTER TABLE public.records ADD COLUMN note text NULL;";

fn docker(args: &[&str]) -> serde_json::Value {
    let output = std::process::Command::new("docker")
        .args(args)
        .output()
        .unwrap();
    assert!(output.status.success(), "Docker QA inspection failed");
    serde_json::from_slice(&output.stdout).unwrap()
}
fn compose(project: &str, file: &std::path::Path, args: &[&str]) {
    let status = std::process::Command::new("/usr/local/bin/docker-compose")
        .args(["-p", project, "-f"])
        .arg(file)
        .args(args)
        .status()
        .unwrap();
    if !status.success() {
        let _ = std::process::Command::new("/usr/local/bin/docker-compose")
            .args(["-p", project, "-f"])
            .arg(file)
            .args(["logs", "--tail", "50", "database"])
            .status();
    }
    assert!(status.success(), "Owned Compose operation failed");
}
struct PgCleanup {
    project: String,
    file: PathBuf,
}
impl Drop for PgCleanup {
    fn drop(&mut self) {
        compose(&self.project, &self.file, &["down", "--remove-orphans"]);
        let volume = format!("{}_postgres-data", self.project);
        let inventory = std::process::Command::new("docker")
            .args([
                "volume",
                "ls",
                "-q",
                "--filter",
                &format!("name=^{volume}$"),
            ])
            .output()
            .unwrap();
        assert!(inventory.status.success());
        if inventory.stdout.is_empty() {
            return;
        }
        let actual = docker(&["volume", "inspect", &volume]);
        assert_eq!(
            actual[0]["Labels"]["com.docker.compose.project"],
            self.project
        );
        assert_eq!(actual[0]["Labels"]["sdlc.task"], "forge-task-delivery");
        assert!(
            std::process::Command::new("docker")
                .args(["volume", "rm", &volume])
                .status()
                .unwrap()
                .success()
        );
    }
}
struct Pg {
    t: ActualDelivery,
    root: PathBuf,
    policy: PathBuf,
    config: serde_json::Value,
    project: String,
    compose_root: PathBuf,
    password: String,
    _cleanup: PgCleanup,
}
impl Drop for Pg {
    fn drop(&mut self) {
        fn copy_json(source: &std::path::Path, target: &std::path::Path) {
            std::fs::create_dir_all(target).unwrap();
            for entry in std::fs::read_dir(source).unwrap().flatten() {
                let path = entry.path();
                let next = target.join(entry.file_name());
                if path.is_dir() {
                    copy_json(&path, &next);
                } else if path.extension().is_some_and(|x| x == "json") {
                    std::fs::copy(path, next).unwrap();
                }
            }
        }
        let export =
            PathBuf::from("/output/pg-evidence").join(self.compose_root.file_name().unwrap());
        std::fs::create_dir_all(&export).unwrap();
        for name in ["operations", "manifests", "backups"] {
            let folder = self.root.join(name);
            if folder.exists() {
                copy_json(&folder, &export.join(name));
            }
        }
        // Actual generated Compose files are retained on the host for panic cleanup/audit.
        let mut files = std::fs::read_dir(&self.compose_root)
            .unwrap()
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "json"))
            .collect::<Vec<_>>();
        files.sort_by_key(|p| std::fs::metadata(p).unwrap().modified().unwrap());
        let file = files.last().unwrap();
        std::fs::copy(file, "/output/pg-compose.json").unwrap();
    }
}
impl Pg {
    async fn new() -> Self {
        let t = ActualDelivery::new().await;
        let case = Uuid::new_v4().simple().to_string();
        let project = std::env::var("CICD_TEST_PG_PROJECT").unwrap();
        let network = std::env::var("CICD_TEST_PG_NETWORK").unwrap();
        let parent = network.strip_suffix("_qa").unwrap();
        let volume = std::env::var("CICD_TEST_PG_VOLUME").unwrap();
        let mount = docker(&["volume", "inspect", &volume])[0]["Mountpoint"]
            .as_str()
            .unwrap()
            .to_owned();
        let controller=docker(&["container","inspect",&format!("{parent}-qa-1")])[0]["NetworkSettings"]["Networks"][&network]["IPAddress"].as_str().unwrap().to_owned();
        let folder = PathBuf::from("/delivery-qa").join(format!("pg-{case}"));
        std::fs::create_dir(&folder).unwrap();
        let root = folder.join("owner");
        let hba = folder.join("pg_hba.conf");
        std::fs::write(&hba,format!("local all postgres trust\nhost all postgres {controller}/32 trust\nhost all forge_reader 0.0.0.0/0 scram-sha-256\nhost all forge_writer 0.0.0.0/0 scram-sha-256\nhost all all 0.0.0.0/0 reject\nhost all all ::/0 reject\n")).unwrap();
        let compose_root =
            PathBuf::from(std::env::var("CICD_TEST_PG_COMPOSE_ROOT").unwrap()).join(&case);
        std::fs::create_dir(&compose_root).unwrap();
        let compose_file = compose_root.join("initial.json");
        let seed = format!("forge_test_pg_{}_seed", &case[..12]);
        let pg_volume = format!("{project}_postgres-data");
        let image = std::env::var("CICD_TEST_PG_IMAGE").unwrap();
        let spec = serde_json::json!({"services":{"database":{"image":image,"pull_policy":"never","init":true,
            "command":["postgres","-c","hba_file=/etc/forge/pg_hba.conf"],
            "environment":{"POSTGRES_HOST_AUTH_METHOD":"trust","POSTGRES_DB":seed},
            "labels":{"sdlc.task":"forge-task-delivery","sdlc.purpose":"disposable-postgres-target"},
            "volumes":[{"type":"volume","source":"data","target":"/var/lib/postgresql/data"},
                {"type":"bind","source":format!("{mount}/pg-{case}/pg_hba.conf"),"target":"/etc/forge/pg_hba.conf","read_only":true}],
            "networks":["owner"],"healthcheck":{"test":["CMD-SHELL",format!("pg_isready -h 127.0.0.1 -U postgres && psql -X -qAt -U postgres -d {seed} -c 'SELECT 1'")],"interval":"1s","timeout":"2s","start_period":"15s","retries":60}}},
            "networks":{"owner":{"external":true,"name":network}},
            "volumes":{"data":{"name":pg_volume,"labels":{"sdlc.task":"forge-task-delivery","sdlc.purpose":"disposable-postgres-data"}}}});
        std::fs::write(&compose_file, serde_json::to_vec(&spec).unwrap()).unwrap();
        std::fs::copy(&compose_file, "/output/pg-compose.json").unwrap();
        // Covers setup panics before Pg exists, so the next test gets fresh resources.
        let cleanup = PgCleanup {
            project: project.clone(),
            file: compose_file.clone(),
        };
        compose(
            &project,
            &compose_file,
            &["up", "--detach", "--pull", "never", "--wait", "database"],
        );
        let ip=docker(&["container","inspect",&format!("{project}-database-1")])[0]["NetworkSettings"]["Networks"][&network]["IPAddress"].as_str().unwrap().to_owned();
        let password = Uuid::new_v4().simple().to_string();
        let mut conn =
            sqlx::PgConnection::connect(&format!("postgres://postgres@{ip}:5432/{seed}"))
                .await
                .unwrap();
        let system: String =
            sqlx::query_scalar("SELECT system_identifier::text FROM pg_control_system()")
                .fetch_one(&mut conn)
                .await
                .unwrap();
        sqlx::raw_sql(&format!("CREATE ROLE forge_reader LOGIN PASSWORD '{password}'; CREATE ROLE forge_writer NOLOGIN PASSWORD '{password}'; REVOKE ALL ON DATABASE {seed} FROM PUBLIC; REVOKE ALL ON DATABASE postgres FROM PUBLIC; REVOKE ALL ON DATABASE template0 FROM PUBLIC; REVOKE ALL ON DATABASE template1 FROM PUBLIC; REVOKE EXECUTE ON FUNCTION pg_catalog.lo_create(oid),pg_catalog.lo_creat(integer),pg_catalog.lo_from_bytea(oid,bytea),pg_catalog.lo_import(text),pg_catalog.lo_import(text,oid),pg_catalog.lo_put(oid,bigint,bytea),pg_catalog.lowrite(integer,bytea),pg_catalog.lo_truncate(integer,integer),pg_catalog.lo_truncate64(integer,bigint),pg_catalog.lo_unlink(oid) FROM PUBLIC,forge_reader,forge_writer;")).execute(&mut conn).await.unwrap();
        let catalog = t.temp.join("seed-catalog");
        std::fs::create_dir(&catalog).unwrap();
        std::fs::write(catalog.join("0001_seed.sql"), SEED).unwrap();
        sqlx::migrate::Migrator::new(catalog.as_path())
            .await
            .unwrap()
            .run(&mut conn)
            .await
            .unwrap();
        sqlx::raw_sql("INSERT INTO public.records(payload) VALUES('alpha'),('beta');")
            .execute(&mut conn)
            .await
            .unwrap();
        sqlx::raw_sql("CREATE VIEW public.qa_history_view AS SELECT version,description,installed_on,success,checksum,execution_time FROM public._sqlx_migrations;")
            .execute(&mut conn)
            .await
            .unwrap();
        conn.close().await.unwrap();
        let daemon = docker(&["info", "--format", "{{json .ID}}"]);
        let policy = t.temp.join("postgres-policy.json");
        let value = serde_json::json!({"schema":"forge/isolated-postgres-policy/v1","projectName":project,
            "daemonId":daemon,"systemIdentifier":system,"controllerIp":controller,"hbaFile":hba,
            "composeFile":compose_file,"composeRoot":compose_root,"postgresImageId":image,"postgresVolumeName":pg_volume,
            "networkName":network,"volumeName":volume,"volumeRoot":"/delivery-qa","initialDatabase":seed,
            "baseRoot":"/work/services-base","pythonBin":"/usr/local/bin/python3","executor":"/work/CI-CD/scripts/postgres-delivery.py",
            "migrationBin":env!("CARGO_BIN_EXE_forge-pg-migrate"),"leaseSeconds":300,
            "checks":{"origin":"http://127.0.0.1:8000","healthPath":"/health","healthBodySha256":hash(b"ok\n"),
                "acceptancePath":"/acceptance","acceptanceBodySha256":hash(b"accepted:records\n")}});
        std::fs::write(&policy, serde_json::to_vec(&value).unwrap()).unwrap();
        let config = serde_json::json!({"project":project,"composeRoot":compose_root,"composeFile":compose_file,
            "daemonId":daemon,"systemIdentifier":system,"ip":ip,"seedDatabase":seed,"sourceDatabase":seed,
            "migrationBin":env!("CARGO_BIN_EXE_forge-pg-migrate")});
        Self {
            t,
            root,
            policy,
            config,
            project,
            compose_root,
            password,
            _cleanup: cleanup,
        }
    }
    fn manifest(&self, readback: &serde_json::Value) -> serde_json::Value {
        serde_json::from_slice(
            &std::fs::read(self.root.join("manifests").join(format!(
                "{}.json",
                readback["currentManifestSha256"].as_str().unwrap()
            )))
            .unwrap(),
        )
        .unwrap()
    }
    async fn build(&mut self, mode: &str, current: Option<&serde_json::Value>) -> DeliveryCommand {
        let binary = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| "target".into());
        std::fs::copy(
            PathBuf::from(binary).join("debug/examples/postgres_target"),
            self.t.source.join("pg-target"),
        )
        .unwrap();
        std::fs::write(self.t.source.join("mode"), mode).unwrap();
        std::fs::write(self.t.source.join("Dockerfile"),"FROM rust:1.88.0@sha256:af306cfa71d987911a781c37b59d7d67d934f49684058f96cf72079c3626bfe0\nCOPY pg-target /app/target\nCOPY mode /app/mode\nEXPOSE 8000\nENTRYPOINT [\"/app/target\"]\n").unwrap();
        std::fs::write(
            self.t.source.join("build_candidate.py"),
            include_bytes!("../helpers/postgres_candidate.py"),
        )
        .unwrap();
        let mut config = self.config.clone();
        config["mode"] = mode.into();
        config["rehearsalDatabase"] = format!(
            "forge_test_pg_{}_rehearsal_{}",
            &Uuid::new_v4().simple().to_string()[..10],
            mode.to_lowercase()
        )
        .into();
        if let Some(current) = current {
            config["sourceDatabase"] = self.manifest(current)["database"].clone();
        }
        let mut migrations = vec![
            serde_json::json!({"version":1,"description":"seed","sql":SEED,"sha256":hash(SEED.as_bytes())}),
        ];
        if mode != "A" {
            migrations.push(serde_json::json!({"version":2,"description":"note","sql":NEXT,"sha256":hash(NEXT.as_bytes())}));
        }
        config["migrations"] = migrations.into();
        std::fs::write(
            self.t.source.join("build.json"),
            serde_json::to_vec(&config).unwrap(),
        )
        .unwrap();
        let mut command = self
            .t
            .build_script_with_timeout(
                mode,
                "python3 -B build_candidate.py",
                Duration::from_secs(300),
            )
            .await
            .0;
        command.expected_manifest_sha256 =
            current.and_then(|r| r["currentManifestSha256"].as_str().map(str::to_owned));
        command
    }
    fn process(&self, command: &DeliveryCommand) -> tokio::process::Command {
        let mut child = self.t.process(command);
        child
            .arg("--postgres")
            .env("CICD_LOCAL_PG_ROOT", &self.root)
            .env("CICD_LOCAL_PG_POLICY", &self.policy)
            .env(
                "CICD_LOCAL_PG_GUARD_URL",
                format!(
                    "postgres://postgres@{}:5432/postgres",
                    self.config["ip"].as_str().unwrap()
                ),
            )
            .env("CICD_LOCAL_PG_RUNTIME_PASSWORD", &self.password);
        child
    }
    async fn execute(&self, command: &DeliveryCommand, mode: Option<&str>) -> serde_json::Value {
        let mut child = self.process(command);
        if let Some(mode) = mode {
            child.arg(mode);
        }
        let output = tokio::time::timeout(Duration::from_secs(330), child.output())
            .await
            .unwrap()
            .unwrap();
        let value: serde_json::Value =
            serde_json::from_slice(&output.stdout).unwrap_or_else(|_| {
                panic!("PG CLI failed: {}", String::from_utf8_lossy(&output.stderr))
            });
        eprintln!("PG_RESULT={value}");
        value
    }
    fn rollback(
        &self,
        command: &DeliveryCommand,
        current: &serde_json::Value,
        key: &str,
    ) -> DeliveryCommand {
        let mut rollback = command.clone();
        rollback.operation_key = format!("pg:rollback:{key}");
        rollback.action = DeliveryAction::Rollback;
        rollback.artifact_id = None;
        rollback.expected_manifest_sha256 =
            current["currentManifestSha256"].as_str().map(str::to_owned);
        rollback
    }
    async fn write(&self, payload: &str) -> i64 {
        let actual = docker(&[
            "container",
            "inspect",
            &format!("{}-application-1", self.project),
        ]);
        let network = std::env::var("CICD_TEST_PG_NETWORK").unwrap();
        let ip = actual[0]["NetworkSettings"]["Networks"][network]["IPAddress"]
            .as_str()
            .unwrap();
        let response = reqwest::Client::new()
            .post(format!("http://{ip}:8000/rows"))
            .json(&serde_json::json!({"payload":payload}))
            .send()
            .await
            .unwrap();
        assert!(response.status().is_success());
        response.json::<serde_json::Value>().await.unwrap()["id"]
            .as_i64()
            .unwrap()
    }
    async fn connection(&self, database: &str) -> sqlx::PgConnection {
        sqlx::PgConnection::connect(&format!(
            "postgres://postgres@{}:5432/{database}",
            self.config["ip"].as_str().unwrap()
        ))
        .await
        .unwrap()
    }
    async fn sql(&self, database: &str, statement: &str) {
        let mut conn = self.connection(database).await;
        sqlx::raw_sql(statement).execute(&mut conn).await.unwrap();
        conn.close().await.unwrap();
    }
    async fn rows(&self, current: &serde_json::Value) {
        let manifest = self.manifest(current);
        let mut conn = self
            .connection(manifest["database"].as_str().unwrap())
            .await;
        let rows: Vec<String> =
            sqlx::query_scalar("SELECT payload FROM public.records ORDER BY id")
                .fetch_all(&mut conn)
                .await
                .unwrap();
        conn.close().await.unwrap();
        assert_eq!(rows, ["alpha", "beta", "gamma", "delta"]);
    }
    async fn access_boundary(&self, current: &serde_json::Value) {
        let manifest = self.manifest(current);
        let target = manifest["database"].as_str().unwrap();
        let mut admin = self.connection("postgres").await;
        let databases: Vec<String> =
            sqlx::query_scalar("SELECT datname FROM pg_database ORDER BY datname")
                .fetch_all(&mut admin)
                .await
                .unwrap();
        admin.close().await.unwrap();
        for role in ["reader", "writer"] {
            for database in &databases {
                let connected = tokio::time::timeout(
                    Duration::from_secs(10),
                    sqlx::PgConnection::connect(&format!(
                        "postgres://forge_{role}:{}@{}:5432/{database}",
                        self.password,
                        self.config["ip"].as_str().unwrap()
                    )),
                )
                .await
                .unwrap();
                if database == target {
                    let mut connected = connected.unwrap();
                    if role == "reader" {
                        for query in [
                            "SELECT pg_catalog.lo_create(0)",
                            "SELECT pg_catalog.lo_creat(0)",
                            "SELECT pg_catalog.lo_from_bytea(0,'\\x00'::bytea)",
                        ] {
                            let error = sqlx::raw_sql(query)
                                .execute(&mut connected)
                                .await
                                .unwrap_err();
                            assert_eq!(
                                error.as_database_error().and_then(|e| e.code()).as_deref(),
                                Some("42501")
                            );
                        }
                    } else {
                        let error = sqlx::raw_sql("UPDATE public.qa_history_view SET description='unauthorized' WHERE version=1;")
                            .execute(&mut connected)
                            .await
                            .expect_err("writer mutated SQLx history through a view");
                        assert_eq!(
                            error.as_database_error().unwrap().code().as_deref(),
                            Some("42501")
                        );
                    }
                    connected.close().await.unwrap();
                } else {
                    assert!(
                        connected.is_err(),
                        "{role} accessed nonselected database {database}"
                    );
                }
            }
        }
        println!("ACTUAL_PG_READER_LO_DENIED_AND_EXCLUSIVE_DATABASE_ACCESS:PASS");
        println!("ACTUAL_PG_WRITER_HISTORY_VIEW_DML_DENIED:PASS");
    }
    async fn negative_restore(&self, command: &DeliveryCommand, current: &serde_json::Value) {
        let manifest = self.manifest(current);
        let source = self.config["seedDatabase"].as_str().unwrap();
        let backup =
            PathBuf::from(manifest["backupDirectory"].as_str().unwrap()).join("database.dump");
        let saved = std::fs::read(&backup).unwrap();
        std::fs::write(&backup, b"corrupt QA dump").unwrap();
        let rollback = self.rollback(command, current, "negative-corrupt");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "backup_corrupt"
        );
        std::fs::write(&backup, &saved).unwrap();
        self.sql("postgres", "CREATE ROLE unknown_writer;").await;
        let rollback = self.rollback(command, current, "negative-role");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "unknown_database_role"
        );
        self.sql("postgres", "DROP ROLE unknown_writer;").await;
        let conn = self.connection(source).await;
        let rollback = self.rollback(command, current, "negative-session");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "unconfirmed_previous_or_unknown_writer"
        );
        conn.close().await.unwrap();
        let failed_db = manifest["database"].as_str().unwrap();
        self.sql(
            failed_db,
            "INSERT INTO public.records(id,payload) VALUES(999,'QA drift');",
        )
        .await;
        let rollback = self.rollback(command, current, "negative-drift");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "failed_candidate_data_drift"
        );
        self.sql(failed_db, "DELETE FROM public.records WHERE id=999;")
            .await;
        self.sql(failed_db, "GRANT INSERT ON public.records TO forge_reader;")
            .await;
        let rollback = self.rollback(command, current, "negative-reader");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "application_reader_can_write_or_create"
        );
        self.sql(
            failed_db,
            "REVOKE INSERT ON public.records FROM forge_reader;",
        )
        .await;
        for (name, grant, revoke) in [
            (
                "reader-column",
                "GRANT UPDATE(payload) ON public.records TO forge_reader;",
                "REVOKE UPDATE(payload) ON public.records FROM forge_reader;",
            ),
            (
                "reader-view",
                "CREATE VIEW public.qa_reader_view AS SELECT id,payload FROM public.records; GRANT INSERT ON public.qa_reader_view TO forge_reader;",
                "DROP VIEW public.qa_reader_view;",
            ),
            (
                "reader-sequence-usage",
                "GRANT USAGE ON SEQUENCE public.records_id_seq TO forge_reader;",
                "REVOKE USAGE ON SEQUENCE public.records_id_seq FROM forge_reader;",
            ),
            (
                "reader-sequence-update",
                "GRANT UPDATE ON SEQUENCE public.records_id_seq TO forge_reader;",
                "REVOKE UPDATE ON SEQUENCE public.records_id_seq FROM forge_reader;",
            ),
            (
                "reader-maintain",
                "GRANT MAINTAIN ON public.records TO forge_reader;",
                "REVOKE MAINTAIN ON public.records FROM forge_reader;",
            ),
        ] {
            self.sql(failed_db, grant).await;
            let rollback = self.rollback(command, current, &format!("negative-{name}"));
            assert_eq!(
                self.execute(&rollback, None).await["reason"],
                "application_reader_can_write_or_create",
                "{name}"
            );
            self.sql(failed_db, revoke).await;
        }
        self.sql(
            failed_db,
            "GRANT EXECUTE ON FUNCTION pg_catalog.lo_create(oid) TO PUBLIC;",
        )
        .await;
        let rollback = self.rollback(command, current, "negative-reader-lo");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "application_reader_can_mutate_large_objects"
        );
        self.sql(
            failed_db,
            "REVOKE EXECUTE ON FUNCTION pg_catalog.lo_create(oid) FROM PUBLIC;",
        )
        .await;
        self.sql(
            failed_db,
            "GRANT UPDATE(description) ON public._sqlx_migrations TO forge_writer;",
        )
        .await;
        let rollback = self.rollback(command, current, "negative-writer-history-column");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "application_writer_can_create_or_mutate_history"
        );
        self.sql(
            failed_db,
            "REVOKE UPDATE(description) ON public._sqlx_migrations FROM forge_writer;",
        )
        .await;
        for (name, grant, revoke, reason) in [
            (
                "writer-history-view",
                "GRANT UPDATE ON public.qa_history_view TO forge_writer;",
                "REVOKE UPDATE ON public.qa_history_view FROM forge_writer;",
                "application_writer_can_mutate_view",
            ),
            (
                "writer-history-view-column",
                "GRANT UPDATE(description) ON public.qa_history_view TO forge_writer;",
                "REVOKE UPDATE(description) ON public.qa_history_view FROM forge_writer;",
                "application_writer_can_mutate_view",
            ),
            (
                "writer-history-rule",
                "CREATE RULE qa_history_write AS ON UPDATE TO public.records DO ALSO UPDATE public._sqlx_migrations SET description='unauthorized' WHERE version=1;",
                "DROP RULE qa_history_write ON public.records;",
                "unsupported_writer_rules",
            ),
            (
                "writer-history-child",
                "CREATE TABLE public.qa_history_child () INHERITS (public._sqlx_migrations);",
                "DROP TABLE public.qa_history_child;",
                "unsupported_history_inheritance",
            ),
            (
                "writer-history-grandchild",
                "CREATE TABLE public.qa_history_child () INHERITS (public._sqlx_migrations); CREATE TABLE public.qa_history_grandchild () INHERITS (public.qa_history_child);",
                "DROP TABLE public.qa_history_grandchild; DROP TABLE public.qa_history_child;",
                "unsupported_history_inheritance",
            ),
            (
                "writer-history-parent",
                "CREATE TABLE public.qa_history_parent (LIKE public._sqlx_migrations); ALTER TABLE public._sqlx_migrations INHERIT public.qa_history_parent;",
                "ALTER TABLE public._sqlx_migrations NO INHERIT public.qa_history_parent; DROP TABLE public.qa_history_parent;",
                "unsupported_history_inheritance",
            ),
            (
                "writer-history-fk-delete",
                "CREATE TABLE public.qa_history_versions(version bigint PRIMARY KEY); INSERT INTO public.qa_history_versions SELECT version FROM public._sqlx_migrations; ALTER TABLE public._sqlx_migrations ADD CONSTRAINT qa_history_fk FOREIGN KEY(version) REFERENCES public.qa_history_versions(version) ON DELETE CASCADE;",
                "ALTER TABLE public._sqlx_migrations DROP CONSTRAINT qa_history_fk; DROP TABLE public.qa_history_versions;",
                "unsupported_history_referential_actions",
            ),
            (
                "writer-history-fk-update",
                "CREATE TABLE public.qa_history_versions(version bigint PRIMARY KEY); INSERT INTO public.qa_history_versions SELECT version FROM public._sqlx_migrations; ALTER TABLE public._sqlx_migrations ADD CONSTRAINT qa_history_fk FOREIGN KEY(version) REFERENCES public.qa_history_versions(version) ON UPDATE CASCADE;",
                "ALTER TABLE public._sqlx_migrations DROP CONSTRAINT qa_history_fk; DROP TABLE public.qa_history_versions;",
                "unsupported_history_referential_actions",
            ),
        ] {
            self.sql(failed_db, grant).await;
            let rollback = self.rollback(command, current, &format!("negative-{name}"));
            assert_eq!(
                self.execute(&rollback, None).await["reason"],
                reason,
                "{name}"
            );
            self.sql(failed_db, revoke).await;
        }
        self.sql(
            failed_db,
            "CREATE SCHEMA pgx; CREATE TABLE pgx.qa_records(id integer);",
        )
        .await;
        let rollback = self.rollback(command, current, "negative-pgx-schema");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "unsupported_database_catalog"
        );
        self.sql(failed_db, "DROP TABLE pgx.qa_records; DROP SCHEMA pgx;")
            .await;
        let mut connection = self.connection(failed_db).await;
        let large_object: i64 = sqlx::query_scalar("SELECT lo_create(0)::bigint")
            .fetch_one(&mut connection)
            .await
            .unwrap();
        connection.close().await.unwrap();
        let rollback = self.rollback(command, current, "negative-large-object");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "unsupported_large_object_inventory"
        );
        self.sql(
            failed_db,
            &format!("SELECT lo_unlink({large_object}::oid);"),
        )
        .await;
        self.sql("postgres", "CREATE ROLE pgx_reader;").await;
        let rollback = self.rollback(command, current, "negative-pgx-role");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "unknown_database_role"
        );
        self.sql("postgres", "DROP ROLE pgx_reader;").await;
        self.sql(
            failed_db,
            "ALTER TABLE public.records OWNER TO forge_writer;",
        )
        .await;
        let rollback = self.rollback(command, current, "negative-owner");
        assert_eq!(
            self.execute(&rollback, None).await["reason"],
            "unknown_application_object_owner"
        );
        self.sql(failed_db, "ALTER TABLE public.records OWNER TO postgres;")
            .await;
        println!(
            "ACTUAL_PG_RESTORE_NEGATIVES=corrupt,role,session,drift,reader,column,view,sequence-usage,sequence-update,maintain,reader-lo,writer-history-column,writer-history-view,writer-history-view-column,writer-history-rule,writer-history-child,writer-history-grandchild,writer-history-parent,writer-history-fk-delete,writer-history-fk-update,pgx-schema,large-object,pgx-role,owner:PASS"
        );
    }
}

#[tokio::test]
async fn sdlc_pg_delivery_actual_migration_restore_rows_sequences_and_write_boundary() {
    for mode in ["H", "C", "M", "B"] {
        let mut t = Pg::new().await;
        let a = t.build("A", None).await;
        let first = t.execute(&a, None).await;
        assert_eq!(latest(&first)["status"], "verified");
        t.access_boundary(&first).await;
        assert_eq!(t.execute(&a, None).await, first);
        assert_eq!(t.write("gamma").await, 3);
        assert_eq!(t.write("delta").await, 4);
        let command = t.build(mode, Some(&first)).await;
        let mut old_reader = sqlx::PgConnection::connect(&format!(
            "postgres://forge_reader:{}@{}:5432/{}",
            t.password,
            t.config["ip"].as_str().unwrap(),
            t.manifest(&first)["database"].as_str().unwrap()
        ))
        .await
        .unwrap();
        let result = t.execute(&command, None).await;
        assert!(
            sqlx::raw_sql("SELECT 1")
                .execute(&mut old_reader)
                .await
                .is_err(),
            "old reader session survived application drain"
        );
        drop(old_reader);
        if mode == "B" {
            assert_eq!(latest(&result)["status"], "verified");
            t.access_boundary(&result).await;
            assert_eq!(
                t.manifest(&result)["databaseFingerprint"]["schema"]["version"],
                2
            );
            t.rows(&result).await;
            assert_eq!(t.write("omega").await, 5);
            let rollback = t.rollback(&command, &result, mode);
            assert_eq!(
                t.execute(&rollback, None).await["reason"],
                "writes_released_previous_snapshot_restore_forbidden"
            );
        } else {
            assert_eq!(latest(&result)["status"], "failed");
            if mode == "H" {
                assert_eq!(latest(&result)["probes"]["health"]["httpStatus"], 503);
            }
            if mode == "C" {
                assert_eq!(latest(&result)["probes"]["health"]["httpStatus"], 200);
                assert_eq!(latest(&result)["probes"]["acceptance"]["httpStatus"], 422);
            }
            if mode == "M" {
                assert_eq!(
                    latest(&result)["reason"],
                    "migration_failed_source_snapshot_preserved"
                );
            }
            assert_eq!(
                result["confirmedManifestSha256"],
                first["confirmedManifestSha256"]
            );
            if mode == "H" {
                t.negative_restore(&command, &result).await;
            }
            let rollback = t.rollback(&command, &result, mode);
            let restored = t.execute(&rollback, None).await;
            assert_eq!(latest(&restored)["status"], "verified");
            t.access_boundary(&restored).await;
            assert_eq!(
                t.manifest(&restored)["descriptor"]["imageId"],
                t.manifest(&first)["descriptor"]["imageId"]
            );
            t.rows(&restored).await;
            assert_eq!(t.write("restored").await, 5);
        }
        println!("ACTUAL_PG_SCENARIO={mode}:PASS");
    }
}

#[tokio::test]
async fn sdlc_pg_delivery_sigkill_checkpoints_hold_without_dangerous_replay() {
    for phase in [
        "backup-verified",
        "migration-intent",
        "restore-intent",
        "release-intent",
        "writes-released",
    ] {
        let mut t = Pg::new().await;
        let a = t.build("A", None).await;
        let first = t.execute(&a, None).await;
        assert_eq!(latest(&first)["status"], "verified");
        assert_eq!(t.write("gamma").await, 3);
        assert_eq!(t.write("delta").await, 4);
        let command = if phase == "restore-intent" {
            let h = t.build("H", Some(&first)).await;
            let failed = t.execute(&h, None).await;
            assert_eq!(latest(&failed)["status"], "failed");
            t.rollback(&h, &failed, "crash")
        } else {
            t.build("B", Some(&first)).await
        };
        let operation = t
            .root
            .join("operations")
            .join(hash(command.operation_key.as_bytes()));
        let resume = t.t.temp.join("never-resume");
        let mut child = t
            .process(&command)
            .env("CICD_TEST_PG_PAUSE_AT", phase)
            .env("CICD_TEST_PG_RESUME_FILE", resume)
            .stdout(std::process::Stdio::null())
            .spawn()
            .unwrap();
        let checkpoint = operation.join(format!("{phase}.json"));
        let deadline = Instant::now() + Duration::from_secs(300);
        while !checkpoint.exists() {
            if let Some(status) = child.try_wait().unwrap() {
                panic!("child stopped before {phase}: {status}");
            }
            assert!(Instant::now() < deadline, "checkpoint deadline: {phase}");
            tokio::time::sleep(Duration::from_millis(50)).await;
        }
        let bytes = std::fs::read(&checkpoint).unwrap();
        let modified = std::fs::metadata(&checkpoint).unwrap().modified().unwrap();
        child.start_kill().unwrap();
        assert!(!child.wait().await.unwrap().success());
        tokio::time::sleep(Duration::from_millis(500)).await;
        let unknown = t.execute(&command, Some("--readback")).await;
        assert_eq!(latest(&unknown)["status"], "unknown");
        assert_eq!(t.execute(&command, None).await, unknown);
        let mut other = command.clone();
        other.operation_key = format!("pg:hold:{phase}");
        other.expected_manifest_sha256 =
            unknown["currentManifestSha256"].as_str().map(str::to_owned);
        assert_eq!(
            t.execute(&other, None).await["reason"],
            "unknown_operation_holds_target"
        );
        let container = if phase == "writes-released" {
            t.rows(&unknown).await;
            assert_eq!(t.write("post-release-survives").await, 5);
            Some(
                docker(&[
                    "container",
                    "inspect",
                    &format!("{}-application-1", t.project),
                ])[0]["Id"]
                    .clone(),
            )
        } else {
            None
        };
        let mut writer_connection = None;
        let mut historical_proof = None;
        if phase == "writes-released" {
            let proof_path = operation.join("verified-checks.json");
            let proof_bytes = std::fs::read(&proof_path).unwrap();
            let mut foreign: serde_json::Value = serde_json::from_slice(&proof_bytes).unwrap();
            foreign["originalOperation"]["operationId"] = Uuid::new_v4().to_string().into();
            std::fs::write(&proof_path, serde_json::to_vec(&foreign).unwrap()).unwrap();
            assert_eq!(
                t.execute(&command, Some("--reconcile")).await["reason"],
                "receipt_binding_mismatch"
            );
            assert!(!operation.join("reconciled.json").exists());
            std::fs::write(&proof_path, &proof_bytes).unwrap();
            for field in ["dataSha256", "sequencesSha256"] {
                let mut foreign: serde_json::Value = serde_json::from_slice(&proof_bytes).unwrap();
                foreign["databaseFingerprint"][field] = "0".repeat(64).into();
                std::fs::write(&proof_path, serde_json::to_vec(&foreign).unwrap()).unwrap();
                assert_eq!(
                    t.execute(&command, Some("--reconcile")).await["reason"],
                    "historical_fingerprint_binding_mismatch"
                );
                assert!(!operation.join("reconciled.json").exists());
                std::fs::write(&proof_path, &proof_bytes).unwrap();
            }
            historical_proof = Some((
                proof_path.clone(),
                proof_bytes,
                std::fs::metadata(&proof_path).unwrap().modified().unwrap(),
            ));
            let database = t.manifest(&unknown)["database"]
                .as_str()
                .unwrap()
                .to_owned();
            writer_connection = Some(
                sqlx::PgConnection::connect(&format!(
                    "postgres://forge_writer:{}@{}:5432/{database}",
                    t.password,
                    t.config["ip"].as_str().unwrap()
                ))
                .await
                .unwrap(),
            );
            t.sql(
                "postgres",
                "GRANT CONNECT ON DATABASE postgres TO forge_reader;",
            )
            .await;
            assert_eq!(
                t.execute(&command, Some("--reconcile")).await["reason"],
                "application_database_connection_scope_changed"
            );
            assert_eq!(
                latest(&t.execute(&command, Some("--readback")).await)["status"],
                "unknown"
            );
            t.sql(
                "postgres",
                "REVOKE CONNECT ON DATABASE postgres FROM forge_reader;",
            )
            .await;
        }
        let recovered = t.execute(&command, Some("--reconcile")).await;
        assert_eq!(recovered["receipt"], unknown["receipt"]);
        if phase == "writes-released" {
            assert_eq!(latest(&recovered)["status"], "verified");
            assert_eq!(latest(&recovered)["containerId"], container.unwrap());
            assert_eq!(t.write("after-reconcile").await, 6);
            let connection = writer_connection.as_mut().unwrap();
            assert_eq!(
                sqlx::query_scalar::<_, i32>("SELECT 1")
                    .fetch_one(connection)
                    .await
                    .unwrap(),
                1
            );
            writer_connection.take().unwrap().close().await.unwrap();
            let (proof_path, proof_bytes, proof_modified) = historical_proof.unwrap();
            assert_eq!(std::fs::read(&proof_path).unwrap(), proof_bytes);
            assert_eq!(
                std::fs::metadata(&proof_path).unwrap().modified().unwrap(),
                proof_modified
            );
            println!("ACTUAL_PG_FOREIGN_PROOF_REJECTED_CURRENT_WRITER_POOL_RECOVERY:PASS");
            let rollback = t.rollback(&command, &recovered, "post-crash-release");
            assert_eq!(
                t.execute(&rollback, None).await["reason"],
                "writes_released_previous_snapshot_restore_forbidden"
            );
        } else {
            assert_eq!(latest(&recovered)["status"], "unknown");
        }
        assert_eq!(std::fs::read(&checkpoint).unwrap(), bytes);
        assert_eq!(
            std::fs::metadata(&checkpoint).unwrap().modified().unwrap(),
            modified
        );
        println!("ACTUAL_PG_SIGKILL={phase}:NO_DANGEROUS_REPLAY");
    }
}

#[tokio::test]
async fn sdlc_pg_delivery_unknown_schema_and_stale_lease_block() {
    {
        let mut t = Pg::new().await;
        let a = t.build("A", None).await;
        let first = t.execute(&a, None).await;
        assert_eq!(latest(&first)["status"], "verified");
        let b = t.build("B", Some(&first)).await;
        let source = t.manifest(&first)["database"].as_str().unwrap().to_owned();
        t.sql(&source,"UPDATE public._sqlx_migrations SET checksum=decode(repeat('ab',48),'hex') WHERE version=1;").await;
        assert_eq!(
            t.execute(&b, None).await["reason"],
            "applied_migration_bytes_changed_or_unknown"
        );
        t.sql(
            &source,
            &format!(
                "UPDATE public._sqlx_migrations SET checksum=decode('{:x}','hex') WHERE version=1;",
                sha2::Sha384::digest(SEED.as_bytes())
            ),
        )
        .await;
        t.sql(
            &source,
            &format!("GRANT CONNECT ON DATABASE {source} TO PUBLIC;"),
        )
        .await;
        assert_eq!(
            t.execute(&b, None).await["reason"],
            "public_database_admission_not_closed"
        );
        t.sql(
            &source,
            &format!("REVOKE ALL ON DATABASE {source} FROM PUBLIC;"),
        )
        .await;
        t.sql(
            &source,
            "ALTER TABLE public.records ADD COLUMN unknown_catalog text;",
        )
        .await;
        assert_eq!(
            t.execute(&b, None).await["reason"],
            "source_schema_unknown_or_incompatible"
        );
        assert!(
            !t.root
                .join("operations")
                .join(hash(b.operation_key.as_bytes()))
                .exists()
        );
        println!("ACTUAL_PG_UNKNOWN_SCHEMA=BLOCKED_BEFORE_EFFECT");
    }
    {
        let mut t = Pg::new().await;
        let a = t.build("A", None).await;
        let mut policy: serde_json::Value =
            serde_json::from_slice(&std::fs::read(&t.policy).unwrap()).unwrap();
        policy["leaseSeconds"] = 10.into();
        std::fs::write(&t.policy, serde_json::to_vec(&policy).unwrap()).unwrap();
        let output = t
            .process(&a)
            .env("CICD_TEST_PG_PAUSE_AT", "drain-intent")
            .env("CICD_TEST_PG_RESUME_FILE", t.t.temp.join("never-resume"))
            .output()
            .await
            .unwrap();
        let result: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
        let operation = t
            .root
            .join("operations")
            .join(hash(a.operation_key.as_bytes()));
        if operation.exists() {
            assert_eq!(latest(&result)["status"], "unknown");
            let diagnostic: serde_json::Value =
                serde_json::from_slice(&std::fs::read(operation.join("diagnostic.json")).unwrap())
                    .unwrap();
            assert_eq!(diagnostic["reason"], "stale_deployment_lease");
            assert!(!operation.join("drained.json").exists());
        } else {
            assert_eq!(result["reason"], "stale_deployment_lease");
        }
        assert!(result["currentManifestSha256"].is_null());
        assert_eq!(
            t.config["seedDatabase"],
            serde_json::json!(policy["initialDatabase"])
        );
        println!("ACTUAL_PG_STALE_LEASE=NO_RELEASE_OR_RETRY");
    }
}
