[package]
name = "cicd-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
jsonwebtoken = { workspace = true }
serde.workspace = true
sqlx.workspace = true
subtle = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
sdlc-auth-core = { path = "/services-base/crates/sdlc-auth-core" }
uuid.workspace = true
