#!/usr/bin/env python3
"""Real PG17 SQL/ACL smoke. Not protocol, lease, Rust suite or receipt proof."""
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import time
from types import SimpleNamespace

project, manifest, executor = sys.argv[1:]
compose = ['docker', '--context', 'rootless', 'compose', '-p', project, '-f', manifest]
pg = compose + ['exec', '-T', 'postgres']


def sql(database, statement, user='postgres', check=True):
    result = subprocess.run(pg + ['psql', '-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-h', '127.0.0.1',
                                 '-U', user, '-d', database, '-c', statement], capture_output=True, text=True)
    if check and result.returncode:
        raise AssertionError(f'{database}: {statement}\n{result.stderr}')
    return result.stdout.strip() if check else result


spec = importlib.util.spec_from_file_location('frozen_pg_owner', executor)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
owner = object.__new__(module.Owner)
owner.sql = sql
owner.pg = SimpleNamespace(ident=lambda s: '"' + s.replace('"', '""') + '"',
                           literal=lambda s: "'" + s.replace("'", "''") + "'")
owner.project = project
owner.command = {'operationKey': 'native-pg17-sql-smoke'}
# Only the SQL methods are under test. There is deliberately no protocol/lease claim.
owner.guard = lambda: None


def blocked(reason, action):
    try:
        action()
    except module.Blocked as exc:
        assert str(exc) == reason, (reason, exc)
    else:
        raise AssertionError(f'expected rejection: {reason}')


assert int(sql('postgres', 'SHOW server_version_num;')) // 10000 == 17
print('PG17_SERVER=' + sql('postgres', 'SELECT version();'), flush=True)
sql('postgres', 'CREATE ROLE forge_reader LOGIN; CREATE ROLE forge_writer LOGIN;')
databases = json.loads(sql('postgres', 'SELECT json_agg(datname) FROM pg_database;'))
for db in databases:
    sql('postgres', f'REVOKE ALL ON DATABASE {owner.pg.ident(db)} FROM PUBLIC;')
target = owner.create_database('candidate')
restored = owner.create_database('restore')
sql(target, 'REVOKE CREATE ON SCHEMA public FROM PUBLIC; '
            'CREATE TABLE public.records (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,payload text); '
            "INSERT INTO public.records(payload) VALUES ('native'); "
            'CREATE TABLE public._sqlx_migrations(version bigint,checksum bytea,success boolean); '
            'CREATE VIEW public.records_view AS SELECT * FROM public.records; '
            'GRANT USAGE ON SCHEMA public TO forge_reader,forge_writer; '
            'GRANT SELECT ON ALL TABLES IN SCHEMA public TO forge_reader;')
owner.reader_permissions(target)
functions = json.loads(sql(target, "SELECT json_agg(oid::regprocedure::text ORDER BY oid) FROM pg_proc "
    "WHERE pronamespace='pg_catalog'::regnamespace AND proname IN "
    "('lo_create','lo_creat','lo_from_bytea','lo_import','lo_put','lowrite','lo_truncate','lo_truncate64','lo_unlink');"))
assert len(functions) == 10, functions
print('PG17_LO_SIGNATURES=' + json.dumps(functions), flush=True)
sql('postgres', f'GRANT CONNECT ON DATABASE {owner.pg.ident(target)} TO forge_reader,forge_writer;')
for statement in ('SELECT lo_create(0)', 'SELECT lo_creat(0)', "SELECT lo_from_bytea(0,'\\x00'::bytea)"):
    result = sql(target, statement, 'forge_reader', False)
    assert result.returncode and 'permission denied for function' in result.stderr, result.stderr
for grant, revoke in [('UPDATE(payload) ON public.records', 'UPDATE(payload) ON public.records'),
                       ('INSERT ON public.records_view', 'INSERT ON public.records_view'),
                       ('MAINTAIN ON public.records', 'MAINTAIN ON public.records'),
                       ('USAGE ON SEQUENCE public.records_id_seq', 'USAGE ON SEQUENCE public.records_id_seq'),
                       ('UPDATE ON SEQUENCE public.records_id_seq', 'UPDATE ON SEQUENCE public.records_id_seq')]:
    sql(target, f'GRANT {grant} TO forge_reader;')
    blocked('application_reader_can_write_or_create', lambda: owner.reader_permissions(target))
    sql(target, f'REVOKE {revoke} FROM forge_reader;')
sql(target, 'GRANT EXECUTE ON FUNCTION lo_create(oid) TO PUBLIC;')
blocked('application_reader_can_mutate_large_objects', lambda: owner.reader_permissions(target))
sql(target, 'REVOKE EXECUTE ON FUNCTION lo_create(oid) FROM PUBLIC;')
sql(target, 'GRANT UPDATE(version) ON public._sqlx_migrations TO forge_writer;')
assert sql(target, "SELECT has_any_column_privilege('forge_writer','public._sqlx_migrations','INSERT,UPDATE,REFERENCES');") == 't'
sql(target, 'REVOKE UPDATE(version) ON public._sqlx_migrations FROM forge_writer;')
inheritance_queries = []
fk_queries = []


def traced_sql(database, statement, *args, **kwargs):
    result = sql(database, statement, *args, **kwargs)
    if 'FROM pg_inherits' in statement:
        inheritance_queries.append((statement, result))
    if 'FROM pg_constraint' in statement:
        fk_queries.append((statement, result))
    return result


owner.sql = traced_sql
try:
    for depth in (1, 2):
        sql(target, 'CREATE TABLE public.qa_history_child () INHERITS (public._sqlx_migrations);')
        if depth == 2:
            sql(target, 'CREATE TABLE public.qa_history_grandchild () INHERITS (public.qa_history_child);')
        table = 'qa_history_child' if depth == 1 else 'qa_history_grandchild'
        query = None
        try:
            sql(target, f'GRANT INSERT ON public.{table} TO forge_writer;')
            assert sql(target, 'SELECT count(*) FROM public._sqlx_migrations;') == '0'
            assert sql(target, 'SELECT count(*) FROM ONLY public._sqlx_migrations;') == '0'
            blocked('unsupported_history_inheritance', lambda: owner.fingerprint(target))
            query, count = inheritance_queries[-1]
            assert 'inhparent=' in query and 'inhrelid=' in query and count == '1'
            sql(target, f"INSERT INTO public.{table}(version,checksum,success) VALUES (99,decode('00','hex'),true);", 'forge_writer')
            assert sql(target, 'SELECT count(*) FROM public._sqlx_migrations;') == '1'
            assert sql(target, 'SELECT count(*) FROM ONLY public._sqlx_migrations;') == '0'
            blocked('unsupported_history_inheritance', lambda: owner.fingerprint(target))
            print(f'PG17_EMPTY_HISTORY_DESCENDANT_DEPTH_{depth}_GUARD_AND_INHERITED_DML:PASS', flush=True)
        finally:
            if depth == 2:
                sql(target, 'DROP TABLE public.qa_history_grandchild;')
            sql(target, 'DROP TABLE public.qa_history_child;')
            if query is not None:
                assert sql(target, query) == '0'
    sql(target, 'CREATE TABLE public.qa_history_parent (LIKE public._sqlx_migrations); '
                'ALTER TABLE public._sqlx_migrations INHERIT public.qa_history_parent; '
                'GRANT SELECT,UPDATE ON public.qa_history_parent TO forge_writer;')
    query = None
    try:
        assert sql(target, 'SELECT count(*) FROM public._sqlx_migrations;') == '0'
        blocked('unsupported_history_inheritance', lambda: owner.fingerprint(target))
        query, count = inheritance_queries[-1]
        assert 'inhparent=' in query and 'inhrelid=' in query and count == '1'
        sql(target, "INSERT INTO public._sqlx_migrations VALUES (99,decode('00','hex'),true);")
        sql(target, 'UPDATE public.qa_history_parent SET success=false;', 'forge_writer')
        assert sql(target, 'SELECT success FROM public._sqlx_migrations WHERE version=99;') == 'f'
        assert sql(target, 'SELECT count(*) FROM ONLY public.qa_history_parent;') == '0'
        blocked('unsupported_history_inheritance', lambda: owner.fingerprint(target))
        print('PG17_HISTORY_AS_CHILD_GUARD_AND_INHERITED_PARENT_DML:PASS', flush=True)
    finally:
        sql(target, 'ALTER TABLE public._sqlx_migrations NO INHERIT public.qa_history_parent; '
                    'DROP TABLE public.qa_history_parent; DELETE FROM public._sqlx_migrations WHERE version=99;')
        if query is not None:
            assert sql(target, query) == '0'
    sql(target, 'ALTER TABLE public._sqlx_migrations ALTER COLUMN version SET DEFAULT 99;')
    try:
        for operation in ('DELETE', 'UPDATE'):
            for action in ('CASCADE', 'SET NULL', 'SET DEFAULT'):
                query = None
                sql(target, 'CREATE TABLE public.qa_history_versions(version bigint PRIMARY KEY); '
                    'INSERT INTO public.qa_history_versions VALUES (99),(100); '
                    "INSERT INTO public._sqlx_migrations VALUES (100,decode('00','hex'),true); "
                    'GRANT SELECT,DELETE,UPDATE ON public.qa_history_versions TO forge_writer; '
                    'ALTER TABLE public._sqlx_migrations ADD CONSTRAINT qa_history_fk '
                    f'FOREIGN KEY(version) REFERENCES public.qa_history_versions(version) ON {operation} {action};')
                try:
                    blocked('unsupported_history_referential_actions', lambda: owner.fingerprint(target))
                    query, count = fk_queries[-1]
                    assert count == '1' and 'confdeltype' in query and 'confupdtype' in query
                    effect = ('DELETE FROM public.qa_history_versions WHERE version=100;' if operation == 'DELETE'
                              else 'UPDATE public.qa_history_versions SET version=101 WHERE version=100;')
                    sql(target, effect, 'forge_writer')
                    if action == 'CASCADE' and operation == 'DELETE':
                        assert sql(target, 'SELECT count(*) FROM public._sqlx_migrations;') == '0'
                    else:
                        expected = {'CASCADE': '101', 'SET NULL': 'NULL', 'SET DEFAULT': '99'}[action]
                        assert sql(target, "SELECT coalesce(version::text,'NULL') FROM public._sqlx_migrations;") == expected
                    print(f"PG17_HISTORY_FK_{operation}_{action.replace(' ', '_')}_GUARD_AND_EFFECT:PASS", flush=True)
                finally:
                    sql(target, 'ALTER TABLE public._sqlx_migrations DROP CONSTRAINT qa_history_fk; '
                        'DELETE FROM public._sqlx_migrations; DROP TABLE public.qa_history_versions;')
                    if query is not None:
                        assert sql(target, query) == '0'
        sql(target, 'CREATE TABLE public.qa_history_versions(version bigint PRIMARY KEY); '
            'INSERT INTO public.qa_history_versions VALUES (100); '
            "INSERT INTO public._sqlx_migrations VALUES (100,decode('00','hex'),true); "
            'GRANT SELECT,DELETE,UPDATE ON public.qa_history_versions TO forge_writer; '
            'ALTER TABLE public._sqlx_migrations ADD CONSTRAINT qa_history_fk '
            'FOREIGN KEY(version) REFERENCES public.qa_history_versions(version) ON DELETE RESTRICT ON UPDATE NO ACTION;')
        try:
            assert sql(target, query) == '0'
            for effect in ('DELETE FROM public.qa_history_versions WHERE version=100;',
                           'UPDATE public.qa_history_versions SET version=101 WHERE version=100;'):
                result = sql(target, effect, 'forge_writer', False)
                assert result.returncode and 'violates foreign key constraint' in result.stderr, result.stderr
            assert sql(target, 'SELECT version FROM public._sqlx_migrations;') == '100'
            print('PG17_HISTORY_FK_PASSIVE_ACTION_CONTRAST:PASS', flush=True)
        finally:
            sql(target, 'ALTER TABLE public._sqlx_migrations DROP CONSTRAINT qa_history_fk; '
                'DELETE FROM public._sqlx_migrations; DROP TABLE public.qa_history_versions;')
    finally:
        sql(target, 'ALTER TABLE public._sqlx_migrations ALTER COLUMN version DROP DEFAULT;')
finally:
    owner.sql = sql
sql(target, 'CREATE SCHEMA pgx_app;')
assert sql(target, "SELECT count(*) FROM pg_namespace WHERE left(nspname,3) <> 'pg_' AND nspname NOT IN ('public','information_schema');") == '1'
sql(target, 'DROP SCHEMA pgx_app;')
lo = sql(target, 'SELECT lo_create(0);')
assert sql(target, 'SELECT count(*) FROM pg_largeobject_metadata;') == '1'
sql(target, f'SELECT lo_unlink({lo}::oid);')
dump = subprocess.run(pg + ['pg_dump', '-U', 'postgres', '-d', target, '--format=custom'], capture_output=True)
assert dump.returncode == 0, dump.stderr
restore = subprocess.run(pg + ['pg_restore', '-U', 'postgres', '-d', restored, '--no-owner',
                               '--no-privileges', '--exit-on-error'], input=dump.stdout, capture_output=True)
assert restore.returncode == 0, restore.stderr
owner.reader_permissions(restored)
assert sql(restored, 'SELECT payload FROM public.records;') == 'native'
print('PG17_RESTORE_PRESERVES_SEALED_BUILTIN_FUNCTION_ACL:PASS', flush=True)
# Hold both roles in real client sessions, then enforce the exact all-DB SQL boundary.
held = []
try:
    for role in ('forge_reader', 'forge_writer'):
        held.append(subprocess.Popen(pg + ['psql', '-X', '-qAt', '-h', '127.0.0.1', '-U', role,
                    '-d', target, '-c', 'SELECT pg_sleep(60);'], stdout=subprocess.PIPE, stderr=subprocess.PIPE))
    for _ in range(50):
        if sql('postgres', "SELECT count(*) FROM pg_stat_activity WHERE usename IN ('forge_reader','forge_writer');") == '2':
            break
        time.sleep(.1)
    else:
        raise AssertionError('real held sessions not established')
    sql('postgres', 'ALTER ROLE forge_reader NOLOGIN; ALTER ROLE forge_writer NOLOGIN;')
    for db in json.loads(sql('postgres', 'SELECT json_agg(datname) FROM pg_database;')):
        sql('postgres', f'REVOKE CONNECT ON DATABASE {owner.pg.ident(db)} FROM forge_reader,forge_writer;')
    sql('postgres', "SELECT pg_terminate_backend(pid,5000) FROM pg_stat_activity WHERE usename IN ('forge_reader','forge_writer');")
    for process in held:
        _, err = process.communicate(timeout=10)
        assert process.returncode and b'terminating connection due to administrator command' in err, err
    owner.source_quiescent(target)
    sql('postgres', f'GRANT CONNECT ON DATABASE {owner.pg.ident(restored)} TO forge_writer;')
    blocked('writer_drain_not_enforced', lambda: owner.source_quiescent(target))
    sql('postgres', f'REVOKE CONNECT ON DATABASE {owner.pg.ident(restored)} FROM forge_writer;')
    owner.source_quiescent(target)
    sql('postgres', f'ALTER ROLE forge_reader LOGIN; GRANT CONNECT ON DATABASE {owner.pg.ident(target)} TO forge_reader;')
    owner.connection_scope(target, False)
    for db in json.loads(sql('postgres', 'SELECT json_agg(datname) FROM pg_database;')):
        for role in ('forge_reader', 'forge_writer'):
            result = sql(db, 'SELECT current_database();', role, False)
            assert (result.returncode == 0) == (db == target and role == 'forge_reader'), (db, role, result.stderr)
    sql('postgres', 'GRANT CONNECT ON DATABASE postgres TO forge_reader;')
    blocked('application_database_connection_scope_changed', lambda: owner.connection_scope(target, False))
    sql('postgres', 'REVOKE CONNECT ON DATABASE postgres FROM forge_reader;')
    owner.connection_scope(target, False)
finally:
    for process in held:
        if process.poll() is None:
            process.terminate()
            process.wait(timeout=10)
print('PG17_REAL_BOTH_ROLE_DRAIN_AND_CANDIDATE_ONLY_READER:PASS', flush=True)
print('ACTUAL_PG17_SQL_SMOKE:PASS', flush=True)
